version: 2
jobs:
  build:
    branches:
      only:
        - development
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@6'
      - run:
          name: install-npm-packages
          command: npm install
      - run:
          name: build-static-site
          command: npx @11ty/eleventy --output=dist
      - run:
          name: deploy-gh-pages
          command: |
            find . -maxdepth 1 ! -name dist ! -name . ! -name .git | xargs rm -rf
            mv dist/*  .
            rm -rf dist/
            git config user.email "ci-build@zinc.coop"
            git config user.name "ci-build"
            git checkout -B gh-pages
            git add -A
            git commit --allow-empty -m "Deploy to GitHub pages [ci skip]"
            git push --force --quiet https://${GITHUB_ACCESS_TOKEN}@github.com/zinc-collective/www.momentpark.com.git gh-pages > /dev/null 2>&1
